# Generated by Django 3.0 on 2021-08-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
