# Generated by Django 3.2.6 on 2021-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210812_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='quality_score',
            field=models.IntegerField(default=0),
        ),
    ]
