# Generated by Django 3.0 on 2021-08-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='city',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='other_city',
            field=models.CharField(default='2', max_length=9999),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='other_city_for_details',
            field=models.CharField(default='3', max_length=9999),
        ),
    ]
