# Generated by Django 3.0 on 2021-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0002_cleaner_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='other_city',
            field=models.CharField(default='Не выезжает', max_length=100),
        ),
    ]
