# Generated by Django 3.0 on 2021-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0003_cleaner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='duration',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
