# Generated by Django 3.0 on 2021-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0003_cleaner_other_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='other_city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
