# Generated by Django 3.0 on 2021-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0004_auto_20210809_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='duration',
            field=models.IntegerField(default=''),
        ),
    ]
