# Generated by Django 3.0 on 2021-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0005_cleaner_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='other_city_for_details',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='other_city',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
