# Generated by Django 3.0 on 2021-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0006_auto_20210811_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='city',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='other_city',
            field=models.CharField(default='2', max_length=9999),
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='other_city_for_details',
            field=models.CharField(default='3', max_length=9999),
        ),
    ]
