# Generated by Django 3.0 on 2021-08-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaners', '0006_auto_20210812_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
