# Generated by Django 3.2.6 on 2021-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('cleaners', '0007_auto_20210813_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='other_city_for_details',
        ),
        migrations.RemoveField(
            model_name='cleaner',
            name='other_city',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='other_city',
            field=models.ManyToManyField(blank=True, to='city.CityList'),
        ),
    ]
