# Generated by Django 3.0 on 2021-08-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210813_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cleaners_id',
            new_name='top_cleaners_id',
        ),
    ]
