# Generated by Django 3.0 on 2021-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210813_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='top_cleaners_durations',
            field=models.IntegerField(default=1),
        ),
    ]
