# Generated by Django 3.2.6 on 2021-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
