# Generated by Django 3.0 on 2021-08-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210813_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cleaner_id',
        ),
    ]
