# Generated by Django 3.0 on 2021-08-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_booking_cleaner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleaners_id',
            field=models.IntegerField(default=0),
        ),
    ]
